maximum:
  max_email_length: 256
  max_name_length: 50
  max_user_per_page: 5
  max_micropost_length: 140

minimum:
  min_password_length: 6
  min_picture_size: 5

gravatar:
  gravatar_size: 80
  gravatar_index_size: 50
  gravatar_follow_size: 30

max_time_password: 2
